# Generated by Django 6.0.5 on 2026-05-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('test_code', models.CharField(help_text='e.g. CBC, LFT, TSH', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sample_type', models.CharField(default='Blood', help_text='e.g. Blood, Urine, Saliva', max_length=100)),
                ('reference_range', models.TextField(help_text='Standard normal ranges for the report')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'lab_test_catalog',
                'ordering': ['name'],
                'unique_together': {('hospital', 'test_code')},
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('prescribed_by', models.CharField(blank=True, help_text='Doctor who requested this test', max_length=255)),
                ('sample_barcode', models.CharField(blank=True, help_text='Unique sample tracker ID', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Sample Collection'), ('collected', 'Sample Collected / Processing'), ('completed', 'Completed / Result Released'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('test_result', models.TextField(blank=True, help_text='Conducted test outcome findings / values')),
                ('technician_notes', models.TextField(blank=True, help_text='Lab analyst observations')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='hospitals.hospital')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='lab.labtest')),
            ],
            options={
                'db_table': 'lab_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
