# Generated by Django 6.0.5 on 2026-05-20 05:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('rooms_beds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('admission_notes', models.TextField(blank=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='admitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='doctors.doctor')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions', to='rooms_beds.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipd_admissions', to='patients.patient')),
            ],
            options={
                'db_table': 'ipd_admissions',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='VitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='°F', max_digits=5, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, help_text='SpO2 %', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='ipd.ipdadmission')),
            ],
            options={
                'db_table': 'ipd_vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
