# Generated by Django 6.0.5 on 2026-05-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('general-ward', 'General Ward'), ('icu', 'ICU'), ('private', 'Private Room'), ('semi-private', 'Semi-Private Room')], default='general-ward', max_length=50)),
                ('charges_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['room_number'],
                'unique_together': {('hospital', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='rooms_beds.room')),
            ],
            options={
                'db_table': 'beds',
                'ordering': ['bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
    ]
