# Generated by Django 6.0.5 on 2026-05-19 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.PositiveIntegerField(help_text='Auto-assigned sequential booking number for this session')),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['schedule__schedule_date', 'appointment_number'],
            },
        ),
    ]
