# Generated by Django 5.2.6 on 2026-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('ONLINE', 'Online Consultation'), ('OFFLINE', 'In-Person / Walk-in')], default='OFFLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department_type',
            field=models.CharField(choices=[('OPD', 'Outpatient Department'), ('IPD', 'Inpatient Department')], default='OPD', max_length=10),
        ),
    ]
