# Generated by Django 6.0.5 on 2026-05-20 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('hospitals', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='webuser',
            name='name',
            field=models.CharField(default='User', max_length=255),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='usertype',
            field=models.CharField(choices=[('super-admin', 'Super Admin'), ('hospital-admin', 'Hospital Admin'), ('frontdesk', 'Frontdesk / Registration Staff'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacy', 'Pharmacy Staff'), ('lab', 'Lab Staff'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.CreateModel(
            name='SuperAdminOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'super_admin_otps',
            },
        ),
    ]
