# Generated by Django 6.0.5 on 2026-05-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('max_patients', models.PositiveIntegerField(default=50, help_text='Maximum number of appointments for this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'db_table': 'schedule',
                'ordering': ['-schedule_date', '-schedule_time'],
            },
        ),
    ]
